/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'MsbMucmemberDelete',
    Heading:'MsbMucmember',
    Roomid:{label :'Roomid'},
    Jid:{label :'Jid'},
    Subscriber:{label :'Subscriber'},
    Nickname:{label :'Nickname'},
    Firstname:{label :'Firstname'},
    Lastname:{label :'Lastname'},
    Url:{label :'Url'},
    Email:{label :'Email'},
    Faqentry:{label :'Faqentry'},
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
    }
    dao.deleteMsbMucmember(jsonObj,function(err,rows) {
        if(err==null){
            parameter.statusCode = 200;
            parameter.statusMessage = 'Successfully created';
        }else{
            parameter.statusCode = err.code;
            parameter.statusMessage = err.message;
        }
        res.redirect(req.session.previouspath);
        console.log(parameter);        
    });
});

module.exports = router;
