/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'MsbPubsubnodeDelete',
    Heading:'MsbPubsubnode',
    Serviceid:{label :'Serviceid'},
    Nodeid:{label :'Nodeid'},
    Leaf:{label :'Leaf'},
    Creationdate:{label :'Creationdate'},
    Modificationdate:{label :'Modificationdate'},
    Parent:{label :'Parent'},
    Deliverpayloads:{label :'Deliverpayloads'},
    Maxpayloadsize:{label :'Maxpayloadsize'},
    Persistitems:{label :'Persistitems'},
    Maxitems:{label :'Maxitems'},
    Notifyconfigchanges:{label :'Notifyconfigchanges'},
    Notifydelete:{label :'Notifydelete'},
    Notifyretract:{label :'Notifyretract'},
    Presencebased:{label :'Presencebased'},
    Senditemsubscribe:{label :'Senditemsubscribe'},
    Publishermodel:{label :'Publishermodel'},
    Subscriptionenabled:{label :'Subscriptionenabled'},
    Configsubscription:{label :'Configsubscription'},
    Accessmodel:{label :'Accessmodel'},
    Payloadtype:{label :'Payloadtype'},
    Bodyxslt:{label :'Bodyxslt'},
    Dataformxslt:{label :'Dataformxslt'},
    Creator:{label :'Creator'},
    Description:{label :'Description'},
    Language:{label :'Language'},
    Name:{label :'Name'},
    Replypolicy:{label :'Replypolicy'},
    Associationpolicy:{label :'Associationpolicy'},
    Maxleafnodes:{label :'Maxleafnodes'},
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
    }
    dao.deleteMsbPubsubnode(jsonObj,function(err,rows) {
        if(err==null){
            parameter.statusCode = 200;
            parameter.statusMessage = 'Successfully created';
        }else{
            parameter.statusCode = err.code;
            parameter.statusMessage = err.message;
        }
        res.redirect(req.session.previouspath);
        console.log(parameter);        
    });
});

module.exports = router;
