/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'MsbMucroomDelete',
    Heading:'MsbMucroom',
    Roomid:{label :'Roomid'},
    Serviceid:{label :'Serviceid'},
    Creationdate:{label :'Creationdate'},
    Modificationdate:{label :'Modificationdate'},
    Name:{label :'Name'},
    Naturalname:{label :'Naturalname'},
    Description:{label :'Description'},
    Lockeddate:{label :'Lockeddate'},
    Emptydate:{label :'Emptydate'},
    Canchangesubject:{label :'Canchangesubject'},
    Maxusers:{label :'Maxusers'},
    Publicroom:{label :'Publicroom'},
    Moderated:{label :'Moderated'},
    Membersonly:{label :'Membersonly'},
    Caninvite:{label :'Caninvite'},
    Roompassword:{label :'Roompassword'},
    Candiscoverjid:{label :'Candiscoverjid'},
    Logenabled:{label :'Logenabled'},
    Subject:{label :'Subject'},
    Rolestobroadcast:{label :'Rolestobroadcast'},
    Usereservednick:{label :'Usereservednick'},
    Canchangenick:{label :'Canchangenick'},
    Canregister:{label :'Canregister'},
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
    }
    dao.deleteMsbMucroom(jsonObj,function(err,rows) {
        if(err==null){
            parameter.statusCode = 200;
            parameter.statusMessage = 'Successfully created';
        }else{
            parameter.statusCode = err.code;
            parameter.statusMessage = err.message;
        }
        res.redirect(req.session.previouspath);
        console.log(parameter);        
    });
});

module.exports = router;
