/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'MsbSessionNew',
    Heading:'MsbSession',
    Sessionid:{label :'Sessionid'},
    Subscriber:{label :'Subscriber'},
    Domain:{label :'Domain'},
    Ipaddress:{label :'Ipaddress'},
    Ipport:{label :'Ipport'},
    Protocol:{label :'Protocol'},
    Starttime:{label :'Starttime'},
    Endtime:{label :'Endtime'},
    Resource:{label :'Resource'},
    Presence:{label :'Presence'},
    Status:{label :'Status'},
    }

router.get('/', sessionChecker, function(req, res, next) {
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
        statusCode:100,
        statusMessage:'',        
        record:{sessionid:'',
        subscriber:'',
        domain:'',
        ipaddress:'',
        ipport:'',
        protocol:'',
        starttime:'',
        endtime:'',
        resource:'',
        presence:'',
        status:'',
        }
    }
    res.render('MsbSessionNewPage',parameter);
    console.log(parameter);
});
router.post('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.body;
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
    }    
    dao.newMsbSession(jsonObj,function(err,rows) {
        if(err==null){
            parameter.statusCode = 200;
            parameter.statusMessage = 'Successfully created';
        }else{
            parameter.statusCode = err.code;
            parameter.statusMessage = err.message;
        }
        parameter.record = jsonObj;
        res.render('MsbSessionNewPage',parameter);
        console.log(parameter);        
    });
});

module.exports = router;
