/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'MsbPubsubsubscriptionNew',
    Heading:'MsbPubsubsubscription',
    Serviceid:{label :'Serviceid'},
    Nodeid:{label :'Nodeid'},
    Id:{label :'Id'},
    Jid:{label :'Jid'},
    Owner:{label :'Owner'},
    State:{label :'State'},
    Deliver:{label :'Deliver'},
    Digest:{label :'Digest'},
    DigestFrequency:{label :'DigestFrequency'},
    Expire:{label :'Expire'},
    Includebody:{label :'Includebody'},
    Showvalues:{label :'Showvalues'},
    Subscriptiontype:{label :'Subscriptiontype'},
    Subscriptiondepth:{label :'Subscriptiondepth'},
    Keyword:{label :'Keyword'},
    }

router.get('/', sessionChecker, function(req, res, next) {
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
        statusCode:100,
        statusMessage:'',        
        record:{serviceid:'',
        nodeid:'',
        id:'',
        jid:'',
        owner:'',
        state:'',
        deliver:'',
        digest:'',
        digestFrequency:'',
        expire:'',
        includebody:'',
        showvalues:'',
        subscriptiontype:'',
        subscriptiondepth:'',
        keyword:'',
        }
    }
    res.render('MsbPubsubsubscriptionNewPage',parameter);
    console.log(parameter);
});
router.post('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.body;
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
    }    
    dao.newMsbPubsubsubscription(jsonObj,function(err,rows) {
        if(err==null){
            parameter.statusCode = 200;
            parameter.statusMessage = 'Successfully created';
        }else{
            parameter.statusCode = err.code;
            parameter.statusMessage = err.message;
        }
        parameter.record = jsonObj;
        res.render('MsbPubsubsubscriptionNewPage',parameter);
        console.log(parameter);        
    });
});

module.exports = router;
