/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'MsbTrafficNew',
    Heading:'MsbTraffic',
    Subscriber:{label :'Subscriber'},
    Account:{label :'Account'},
    From:{label :'From'},
    To:{label :'To'},
    Counter:{label :'Counter'},
    Type:{label :'Type'},
    LastUpdate:{label :'LastUpdate'},
    Status:{label :'Status'},
    }

router.get('/', sessionChecker, function(req, res, next) {
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
        statusCode:100,
        statusMessage:'',        
        record:{subscriber:'',
        account:'',
        from:'',
        to:'',
        counter:'',
        type:'',
        lastUpdate:'',
        status:'',
        }
    }
    res.render('MsbTrafficNewPage',parameter);
    console.log(parameter);
});
router.post('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.body;
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
    }    
    dao.newMsbTraffic(jsonObj,function(err,rows) {
        if(err==null){
            parameter.statusCode = 200;
            parameter.statusMessage = 'Successfully created';
        }else{
            parameter.statusCode = err.code;
            parameter.statusMessage = err.message;
        }
        parameter.record = jsonObj;
        res.render('MsbTrafficNewPage',parameter);
        console.log(parameter);        
    });
});

module.exports = router;
