/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'MsbMucmemberNew',
    Heading:'MsbMucmember',
    Roomid:{label :'Roomid'},
    Jid:{label :'Jid'},
    Subscriber:{label :'Subscriber'},
    Nickname:{label :'Nickname'},
    Firstname:{label :'Firstname'},
    Lastname:{label :'Lastname'},
    Url:{label :'Url'},
    Email:{label :'Email'},
    Faqentry:{label :'Faqentry'},
    }

router.get('/', sessionChecker, function(req, res, next) {
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
        statusCode:100,
        statusMessage:'',        
        record:{roomid:'',
        jid:'',
        subscriber:'',
        nickname:'',
        firstname:'',
        lastname:'',
        url:'',
        email:'',
        faqentry:'',
        }
    }
    res.render('MsbMucmemberNewPage',parameter);
    console.log(parameter);
});
router.post('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.body;
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
    }    
    dao.newMsbMucmember(jsonObj,function(err,rows) {
        if(err==null){
            parameter.statusCode = 200;
            parameter.statusMessage = 'Successfully created';
        }else{
            parameter.statusCode = err.code;
            parameter.statusMessage = err.message;
        }
        parameter.record = jsonObj;
        res.render('MsbMucmemberNewPage',parameter);
        console.log(parameter);        
    });
});

module.exports = router;
