/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'MsbSubscriberNew',
    Heading:'MsbSubscriber',
    Subscriber:{label :'Subscriber'},
    Password:{label :'Password'},
    Name:{label :'Name'},
    Email:{label :'Email'},
    Creationdate:{label :'Creationdate'},
    Modificationdate:{label :'Modificationdate'},
    Subtype:{label :'Subtype'},
    Account:{label :'Account'},
    Userkey:{label :'Userkey'},
    }

router.get('/', sessionChecker, function(req, res, next) {
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
        statusCode:100,
        statusMessage:'',        
        record:{subscriber:'',
        password:'',
        name:'',
        email:'',
        creationdate:'',
        modificationdate:'',
        subtype:'',
        account:'',
        userkey:'',
        }
    }
    res.render('MsbSubscriberNewPage',parameter);
    console.log(parameter);
});
router.post('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.body;
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
    }    
    dao.newMsbSubscriber(jsonObj,function(err,rows) {
        if(err==null){
            parameter.statusCode = 200;
            parameter.statusMessage = 'Successfully created';
        }else{
            parameter.statusCode = err.code;
            parameter.statusMessage = err.message;
        }
        parameter.record = jsonObj;
        res.render('MsbSubscriberNewPage',parameter);
        console.log(parameter);        
    });
});

module.exports = router;
