/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'MsbSubscribertypeRead',
    Heading:'MsbSubscribertype',
    Subtype:{label :'Subtype'},
    Description:{label :'Description'},
    MsbSubscriber:{Heading:'MsbSubscriber',
        Subscriber:{header:'Subscriber'},
        Password:{header:'Password'},
        Name:{header:'Name'},
        Email:{header:'Email'},
        Creationdate:{header:'Creationdate'},
        Modificationdate:{header:'Modificationdate'},
        Subtype:{header:'Subtype'},
        Account:{header:'Account'},
        Userkey:{header:'Userkey'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    jsonObj.rowid = 0;
    req.session.previouspath = 'readMsbSubscribertype?'+req._parsedUrl.query;
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
    }
    var readMsbSubscribertype = new Promise((resolve, reject) => {
        setTimeout(() => {
            dao.readMsbSubscribertype(jsonObj,function(err,rows) {
                if(err) res.status(err.code).end();
                else{
                    if(rows[0]===undefined) res.redirect('/searchMsbSubscribertype');
                    else{ 
                        jsonObj = rows[0];
                        resolve(jsonObj);
                    }
                }
            });
        },1000);
    });
    
    var msbSubscriber = new Promise((resolve, reject) => {
        setTimeout(() => {
            dao.readMsbSubscribertype(jsonObj,function(err,rows) {
                jsonObj = rows[0];
                dao.readMsbSubscribertypeMsbSubscriber(jsonObj,function(err,rows) {
                    jsonObj.msbSubscriber = rows;
                    resolve(jsonObj);
                });
            });        
        },1000);
    });
    
    var sendResult = (results) => {
        console.log(jsonObj)
        parameter.record = jsonObj;        
        res.render('MsbSubscribertypeReadPage',parameter);
    }    
    Promise.all([readMsbSubscribertype,msbSubscriber]).then(sendResult);
});

module.exports = router;
