/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'MsbSessionRead',
    Heading:'MsbSession',
    Sessionid:{label :'Sessionid'},
    Subscriber:{label :'Subscriber'},
    Domain:{label :'Domain'},
    Ipaddress:{label :'Ipaddress'},
    Ipport:{label :'Ipport'},
    Protocol:{label :'Protocol'},
    Starttime:{label :'Starttime'},
    Endtime:{label :'Endtime'},
    Resource:{label :'Resource'},
    Presence:{label :'Presence'},
    Status:{label :'Status'},
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    jsonObj.rowid = 0;
    req.session.previouspath = 'readMsbSession?'+req._parsedUrl.query;
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
    }
    var readMsbSession = new Promise((resolve, reject) => {
        setTimeout(() => {
            dao.readMsbSession(jsonObj,function(err,rows) {
                if(err) res.status(err.code).end();
                else{
                    if(rows[0]===undefined) res.redirect('/searchMsbSession');
                    else{ 
                        jsonObj = rows[0];
                        resolve(jsonObj);
                    }
                }
            });
        },1000);
    });
    
    var sendResult = (results) => {
        console.log(jsonObj)
        parameter.record = jsonObj;        
        res.render('MsbSessionReadPage',parameter);
    }    
    Promise.all([readMsbSession]).then(sendResult);
});

module.exports = router;
