/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'MsbMucaffiliationRead',
    Heading:'MsbMucaffiliation',
    Roomid:{label :'Roomid'},
    Jid:{label :'Jid'},
    Affiliation:{label :'Affiliation'},
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    jsonObj.rowid = 0;
    req.session.previouspath = 'readMsbMucaffiliation?'+req._parsedUrl.query;
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
    }
    var readMsbMucaffiliation = new Promise((resolve, reject) => {
        setTimeout(() => {
            dao.readMsbMucaffiliation(jsonObj,function(err,rows) {
                if(err) res.status(err.code).end();
                else{
                    if(rows[0]===undefined) res.redirect('/searchMsbMucaffiliation');
                    else{ 
                        jsonObj = rows[0];
                        resolve(jsonObj);
                    }
                }
            });
        },1000);
    });
    
    var sendResult = (results) => {
        console.log(jsonObj)
        parameter.record = jsonObj;        
        res.render('MsbMucaffiliationReadPage',parameter);
    }    
    Promise.all([readMsbMucaffiliation]).then(sendResult);
});

module.exports = router;
