/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'MsbPubsubsubscriptionRead',
    Heading:'MsbPubsubsubscription',
    Serviceid:{label :'Serviceid'},
    Nodeid:{label :'Nodeid'},
    Id:{label :'Id'},
    Jid:{label :'Jid'},
    Owner:{label :'Owner'},
    State:{label :'State'},
    Deliver:{label :'Deliver'},
    Digest:{label :'Digest'},
    DigestFrequency:{label :'DigestFrequency'},
    Expire:{label :'Expire'},
    Includebody:{label :'Includebody'},
    Showvalues:{label :'Showvalues'},
    Subscriptiontype:{label :'Subscriptiontype'},
    Subscriptiondepth:{label :'Subscriptiondepth'},
    Keyword:{label :'Keyword'},
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    jsonObj.rowid = 0;
    req.session.previouspath = 'readMsbPubsubsubscription?'+req._parsedUrl.query;
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
    }
    var readMsbPubsubsubscription = new Promise((resolve, reject) => {
        setTimeout(() => {
            dao.readMsbPubsubsubscription(jsonObj,function(err,rows) {
                if(err) res.status(err.code).end();
                else{
                    if(rows[0]===undefined) res.redirect('/searchMsbPubsubsubscription');
                    else{ 
                        jsonObj = rows[0];
                        resolve(jsonObj);
                    }
                }
            });
        },1000);
    });
    
    var sendResult = (results) => {
        console.log(jsonObj)
        parameter.record = jsonObj;        
        res.render('MsbPubsubsubscriptionReadPage',parameter);
    }    
    Promise.all([readMsbPubsubsubscription]).then(sendResult);
});

module.exports = router;
