/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'MsbMucmemberRead',
    Heading:'MsbMucmember',
    Roomid:{label :'Roomid'},
    Jid:{label :'Jid'},
    Subscriber:{label :'Subscriber'},
    Nickname:{label :'Nickname'},
    Firstname:{label :'Firstname'},
    Lastname:{label :'Lastname'},
    Url:{label :'Url'},
    Email:{label :'Email'},
    Faqentry:{label :'Faqentry'},
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    jsonObj.rowid = 0;
    req.session.previouspath = 'readMsbMucmember?'+req._parsedUrl.query;
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
    }
    var readMsbMucmember = new Promise((resolve, reject) => {
        setTimeout(() => {
            dao.readMsbMucmember(jsonObj,function(err,rows) {
                if(err) res.status(err.code).end();
                else{
                    if(rows[0]===undefined) res.redirect('/searchMsbMucmember');
                    else{ 
                        jsonObj = rows[0];
                        resolve(jsonObj);
                    }
                }
            });
        },1000);
    });
    
    var sendResult = (results) => {
        console.log(jsonObj)
        parameter.record = jsonObj;        
        res.render('MsbMucmemberReadPage',parameter);
    }    
    Promise.all([readMsbMucmember]).then(sendResult);
});

module.exports = router;
