/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'MsbRosterRead',
    Heading:'MsbRoster',
    Rosterid:{label :'Rosterid'},
    Subscriber:{label :'Subscriber'},
    Jid:{label :'Jid'},
    Sub:{label :'Sub'},
    Ask:{label :'Ask'},
    Recv:{label :'Recv'},
    Nick:{label :'Nick'},
    Key:{label :'Key'},
    MsbRostergroups:{Heading:'MsbRostergroups',
        Rosterid:{header:'Rosterid'},
        Rank:{header:'Rank'},
        Groupname:{header:'Groupname'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    jsonObj.rowid = 0;
    req.session.previouspath = 'readMsbRoster?'+req._parsedUrl.query;
    parameter = {
        session: req.session,
        cookies: req.cookies,
        resource: appresource,
        dateFormat: dateFormat,
    }
    var readMsbRoster = new Promise((resolve, reject) => {
        setTimeout(() => {
            dao.readMsbRoster(jsonObj,function(err,rows) {
                if(err) res.status(err.code).end();
                else{
                    if(rows[0]===undefined) res.redirect('/searchMsbRoster');
                    else{ 
                        jsonObj = rows[0];
                        resolve(jsonObj);
                    }
                }
            });
        },1000);
    });
    
    var msbRostergroups = new Promise((resolve, reject) => {
        setTimeout(() => {
            dao.readMsbRoster(jsonObj,function(err,rows) {
                jsonObj = rows[0];
                dao.readMsbRosterMsbRostergroups(jsonObj,function(err,rows) {
                    jsonObj.msbRostergroups = rows;
                    resolve(jsonObj);
                });
            });        
        },1000);
    });
    
    var sendResult = (results) => {
        console.log(jsonObj)
        parameter.record = jsonObj;        
        res.render('MsbRosterReadPage',parameter);
    }    
    Promise.all([readMsbRoster,msbRostergroups]).then(sendResult);
});

module.exports = router;
