/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'MsbMucaffiliationSearch',
    Heading:'MsbMucaffiliation',
    Roomid:{label :'Roomid'},
    Jid:{label :'Jid'},
    Affiliation:{label :'Affiliation'},
    MsbMucaffiliation:{Heading:'MsbMucaffiliation',
        Roomid:{header:'Roomid'},
        Jid:{header:'Jid'},
        Affiliation:{header:'Affiliation'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    req.session.previouspath = 'searchMsbMucaffiliation?'+req._parsedUrl.query;
    dao.searchMsbMucaffiliation(jsonObj,function(err,rows) {
        parameter = {
            session: req.session,
            cookies: req.cookies,
            resource: appresource,
            dateFormat: dateFormat,
            records: rows,
        }
        res.render('MsbMucaffiliationSearchPage',parameter);
        console.log(parameter);        
    })
});

module.exports = router;
