/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'MsbRevenueSearch',
    Heading:'MsbRevenue',
    Subscriber:{label :'Subscriber'},
    Account:{label :'Account'},
    From:{label :'From'},
    To:{label :'To'},
    Debit:{label :'Debit'},
    Credit:{label :'Credit'},
    Description:{label :'Description'},
    Activity:{label :'Activity'},
    Datetime:{label :'Datetime'},
    Status:{label :'Status'},
    MsbRevenue:{Heading:'MsbRevenue',
        Subscriber:{header:'Subscriber'},
        Account:{header:'Account'},
        From:{header:'From'},
        To:{header:'To'},
        Debit:{header:'Debit'},
        Credit:{header:'Credit'},
        Description:{header:'Description'},
        Activity:{header:'Activity'},
        Datetime:{header:'Datetime'},
        Status:{header:'Status'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    req.session.previouspath = 'searchMsbRevenue?'+req._parsedUrl.query;
    dao.searchMsbRevenue(jsonObj,function(err,rows) {
        parameter = {
            session: req.session,
            cookies: req.cookies,
            resource: appresource,
            dateFormat: dateFormat,
            records: rows,
        }
        res.render('MsbRevenueSearchPage',parameter);
        console.log(parameter);        
    })
});

module.exports = router;
