/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'MsbTrafficSearch',
    Heading:'MsbTraffic',
    Subscriber:{label :'Subscriber'},
    Account:{label :'Account'},
    From:{label :'From'},
    To:{label :'To'},
    Counter:{label :'Counter'},
    Type:{label :'Type'},
    LastUpdate:{label :'LastUpdate'},
    Status:{label :'Status'},
    MsbTraffic:{Heading:'MsbTraffic',
        Subscriber:{header:'Subscriber'},
        Account:{header:'Account'},
        From:{header:'From'},
        To:{header:'To'},
        Counter:{header:'Counter'},
        Type:{header:'Type'},
        LastUpdate:{header:'LastUpdate'},
        Status:{header:'Status'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    req.session.previouspath = 'searchMsbTraffic?'+req._parsedUrl.query;
    dao.searchMsbTraffic(jsonObj,function(err,rows) {
        parameter = {
            session: req.session,
            cookies: req.cookies,
            resource: appresource,
            dateFormat: dateFormat,
            records: rows,
        }
        res.render('MsbTrafficSearchPage',parameter);
        console.log(parameter);        
    })
});

module.exports = router;
