/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'MsbPubsubnodeSearch',
    Heading:'MsbPubsubnode',
    Serviceid:{label :'Serviceid'},
    Nodeid:{label :'Nodeid'},
    Leaf:{label :'Leaf'},
    Creationdate:{label :'Creationdate'},
    Modificationdate:{label :'Modificationdate'},
    Parent:{label :'Parent'},
    Deliverpayloads:{label :'Deliverpayloads'},
    Maxpayloadsize:{label :'Maxpayloadsize'},
    Persistitems:{label :'Persistitems'},
    Maxitems:{label :'Maxitems'},
    Notifyconfigchanges:{label :'Notifyconfigchanges'},
    Notifydelete:{label :'Notifydelete'},
    Notifyretract:{label :'Notifyretract'},
    Presencebased:{label :'Presencebased'},
    Senditemsubscribe:{label :'Senditemsubscribe'},
    Publishermodel:{label :'Publishermodel'},
    Subscriptionenabled:{label :'Subscriptionenabled'},
    Configsubscription:{label :'Configsubscription'},
    Accessmodel:{label :'Accessmodel'},
    Payloadtype:{label :'Payloadtype'},
    Bodyxslt:{label :'Bodyxslt'},
    Dataformxslt:{label :'Dataformxslt'},
    Creator:{label :'Creator'},
    Description:{label :'Description'},
    Language:{label :'Language'},
    Name:{label :'Name'},
    Replypolicy:{label :'Replypolicy'},
    Associationpolicy:{label :'Associationpolicy'},
    Maxleafnodes:{label :'Maxleafnodes'},
    MsbPubsubnode:{Heading:'MsbPubsubnode',
        Serviceid:{header:'Serviceid'},
        Nodeid:{header:'Nodeid'},
        Leaf:{header:'Leaf'},
        Creationdate:{header:'Creationdate'},
        Modificationdate:{header:'Modificationdate'},
        Parent:{header:'Parent'},
        Deliverpayloads:{header:'Deliverpayloads'},
        Maxpayloadsize:{header:'Maxpayloadsize'},
        Persistitems:{header:'Persistitems'},
        Maxitems:{header:'Maxitems'},
        Notifyconfigchanges:{header:'Notifyconfigchanges'},
        Notifydelete:{header:'Notifydelete'},
        Notifyretract:{header:'Notifyretract'},
        Presencebased:{header:'Presencebased'},
        Senditemsubscribe:{header:'Senditemsubscribe'},
        Publishermodel:{header:'Publishermodel'},
        Subscriptionenabled:{header:'Subscriptionenabled'},
        Configsubscription:{header:'Configsubscription'},
        Accessmodel:{header:'Accessmodel'},
        Payloadtype:{header:'Payloadtype'},
        Bodyxslt:{header:'Bodyxslt'},
        Dataformxslt:{header:'Dataformxslt'},
        Creator:{header:'Creator'},
        Description:{header:'Description'},
        Language:{header:'Language'},
        Name:{header:'Name'},
        Replypolicy:{header:'Replypolicy'},
        Associationpolicy:{header:'Associationpolicy'},
        Maxleafnodes:{header:'Maxleafnodes'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    req.session.previouspath = 'searchMsbPubsubnode?'+req._parsedUrl.query;
    dao.searchMsbPubsubnode(jsonObj,function(err,rows) {
        parameter = {
            session: req.session,
            cookies: req.cookies,
            resource: appresource,
            dateFormat: dateFormat,
            records: rows,
        }
        res.render('MsbPubsubnodeSearchPage',parameter);
        console.log(parameter);        
    })
});

module.exports = router;
