/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'MsbRostergroupsSearch',
    Heading:'MsbRostergroups',
    Rosterid:{label :'Rosterid'},
    Rank:{label :'Rank'},
    Groupname:{label :'Groupname'},
    MsbRostergroups:{Heading:'MsbRostergroups',
        Rosterid:{header:'Rosterid'},
        Rank:{header:'Rank'},
        Groupname:{header:'Groupname'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    req.session.previouspath = 'searchMsbRostergroups?'+req._parsedUrl.query;
    dao.searchMsbRostergroups(jsonObj,function(err,rows) {
        parameter = {
            session: req.session,
            cookies: req.cookies,
            resource: appresource,
            dateFormat: dateFormat,
            records: rows,
        }
        res.render('MsbRostergroupsSearchPage',parameter);
        console.log(parameter);        
    })
});

module.exports = router;
