/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'MsbPubsubsubscriberSearch',
    Heading:'MsbPubsubsubscriber',
    Serviceid:{label :'Serviceid'},
    Nodeid:{label :'Nodeid'},
    Jid:{label :'Jid'},
    Associationtype:{label :'Associationtype'},
    MsbPubsubsubscriber:{Heading:'MsbPubsubsubscriber',
        Serviceid:{header:'Serviceid'},
        Nodeid:{header:'Nodeid'},
        Jid:{header:'Jid'},
        Associationtype:{header:'Associationtype'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    req.session.previouspath = 'searchMsbPubsubsubscriber?'+req._parsedUrl.query;
    dao.searchMsbPubsubsubscriber(jsonObj,function(err,rows) {
        parameter = {
            session: req.session,
            cookies: req.cookies,
            resource: appresource,
            dateFormat: dateFormat,
            records: rows,
        }
        res.render('MsbPubsubsubscriberSearchPage',parameter);
        console.log(parameter);        
    })
});

module.exports = router;
