/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'MsbRemoteserverSearch',
    Heading:'MsbRemoteserver',
    Xmppdomain:{label :'Xmppdomain'},
    Remoteaddress:{label :'Remoteaddress'},
    Remoteport:{label :'Remoteport'},
    User:{label :'User'},
    Password:{label :'Password'},
    Permission:{label :'Permission'},
    MsbRemoteserver:{Heading:'MsbRemoteserver',
        Xmppdomain:{header:'Xmppdomain'},
        Remoteaddress:{header:'Remoteaddress'},
        Remoteport:{header:'Remoteport'},
        User:{header:'User'},
        Password:{header:'Password'},
        Permission:{header:'Permission'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    req.session.previouspath = 'searchMsbRemoteserver?'+req._parsedUrl.query;
    dao.searchMsbRemoteserver(jsonObj,function(err,rows) {
        parameter = {
            session: req.session,
            cookies: req.cookies,
            resource: appresource,
            dateFormat: dateFormat,
            records: rows,
        }
        res.render('MsbRemoteserverSearchPage',parameter);
        console.log(parameter);        
    })
});

module.exports = router;
