/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'MsbMucserviceSearch',
    Heading:'MsbMucservice',
    Serviceid:{label :'Serviceid'},
    Domain:{label :'Domain'},
    Subdomain:{label :'Subdomain'},
    Description:{label :'Description'},
    Ishidden:{label :'Ishidden'},
    MsbMucservice:{Heading:'MsbMucservice',
        Serviceid:{header:'Serviceid'},
        Domain:{header:'Domain'},
        Subdomain:{header:'Subdomain'},
        Description:{header:'Description'},
        Ishidden:{header:'Ishidden'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    req.session.previouspath = 'searchMsbMucservice?'+req._parsedUrl.query;
    dao.searchMsbMucservice(jsonObj,function(err,rows) {
        parameter = {
            session: req.session,
            cookies: req.cookies,
            resource: appresource,
            dateFormat: dateFormat,
            records: rows,
        }
        res.render('MsbMucserviceSearchPage',parameter);
        console.log(parameter);        
    })
});

module.exports = router;
