/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'MsbPubsubsubscriptionSearch',
    Heading:'MsbPubsubsubscription',
    Serviceid:{label :'Serviceid'},
    Nodeid:{label :'Nodeid'},
    Id:{label :'Id'},
    Jid:{label :'Jid'},
    Owner:{label :'Owner'},
    State:{label :'State'},
    Deliver:{label :'Deliver'},
    Digest:{label :'Digest'},
    DigestFrequency:{label :'DigestFrequency'},
    Expire:{label :'Expire'},
    Includebody:{label :'Includebody'},
    Showvalues:{label :'Showvalues'},
    Subscriptiontype:{label :'Subscriptiontype'},
    Subscriptiondepth:{label :'Subscriptiondepth'},
    Keyword:{label :'Keyword'},
    MsbPubsubsubscription:{Heading:'MsbPubsubsubscription',
        Serviceid:{header:'Serviceid'},
        Nodeid:{header:'Nodeid'},
        Id:{header:'Id'},
        Jid:{header:'Jid'},
        Owner:{header:'Owner'},
        State:{header:'State'},
        Deliver:{header:'Deliver'},
        Digest:{header:'Digest'},
        DigestFrequency:{header:'DigestFrequency'},
        Expire:{header:'Expire'},
        Includebody:{header:'Includebody'},
        Showvalues:{header:'Showvalues'},
        Subscriptiontype:{header:'Subscriptiontype'},
        Subscriptiondepth:{header:'Subscriptiondepth'},
        Keyword:{header:'Keyword'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    req.session.previouspath = 'searchMsbPubsubsubscription?'+req._parsedUrl.query;
    dao.searchMsbPubsubsubscription(jsonObj,function(err,rows) {
        parameter = {
            session: req.session,
            cookies: req.cookies,
            resource: appresource,
            dateFormat: dateFormat,
            records: rows,
        }
        res.render('MsbPubsubsubscriptionSearchPage',parameter);
        console.log(parameter);        
    })
});

module.exports = router;
