/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'MsbPubsubaffiliationSearch',
    Heading:'MsbPubsubaffiliation',
    Serviceid:{label :'Serviceid'},
    Nodeid:{label :'Nodeid'},
    Jid:{label :'Jid'},
    Affiliation:{label :'Affiliation'},
    MsbPubsubaffiliation:{Heading:'MsbPubsubaffiliation',
        Serviceid:{header:'Serviceid'},
        Nodeid:{header:'Nodeid'},
        Jid:{header:'Jid'},
        Affiliation:{header:'Affiliation'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    req.session.previouspath = 'searchMsbPubsubaffiliation?'+req._parsedUrl.query;
    dao.searchMsbPubsubaffiliation(jsonObj,function(err,rows) {
        parameter = {
            session: req.session,
            cookies: req.cookies,
            resource: appresource,
            dateFormat: dateFormat,
            records: rows,
        }
        res.render('MsbPubsubaffiliationSearchPage',parameter);
        console.log(parameter);        
    })
});

module.exports = router;
