/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'MsbMucroompropSearch',
    Heading:'MsbMucroomprop',
    Roomid:{label :'Roomid'},
    Name:{label :'Name'},
    Propvalue:{label :'Propvalue'},
    MsbMucroomprop:{Heading:'MsbMucroomprop',
        Roomid:{header:'Roomid'},
        Name:{header:'Name'},
        Propvalue:{header:'Propvalue'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    req.session.previouspath = 'searchMsbMucroomprop?'+req._parsedUrl.query;
    dao.searchMsbMucroomprop(jsonObj,function(err,rows) {
        parameter = {
            session: req.session,
            cookies: req.cookies,
            resource: appresource,
            dateFormat: dateFormat,
            records: rows,
        }
        res.render('MsbMucroompropSearchPage',parameter);
        console.log(parameter);        
    })
});

module.exports = router;
