/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'MsbPubsubitemSearch',
    Heading:'MsbPubsubitem',
    Serviceid:{label :'Serviceid'},
    Nodeid:{label :'Nodeid'},
    Id:{label :'Id'},
    Jid:{label :'Jid'},
    Creationdate:{label :'Creationdate'},
    Payload:{label :'Payload'},
    MsbPubsubitem:{Heading:'MsbPubsubitem',
        Serviceid:{header:'Serviceid'},
        Nodeid:{header:'Nodeid'},
        Id:{header:'Id'},
        Jid:{header:'Jid'},
        Creationdate:{header:'Creationdate'},
        Payload:{header:'Payload'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    req.session.previouspath = 'searchMsbPubsubitem?'+req._parsedUrl.query;
    dao.searchMsbPubsubitem(jsonObj,function(err,rows) {
        parameter = {
            session: req.session,
            cookies: req.cookies,
            resource: appresource,
            dateFormat: dateFormat,
            records: rows,
        }
        res.render('MsbPubsubitemSearchPage',parameter);
        console.log(parameter);        
    })
});

module.exports = router;
