/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'MsbAccountSearch',
    Heading:'MsbAccount',
    Username:{label :'Username'},
    Password:{label :'Password'},
    Account:{label :'Account'},
    Email:{label :'Email'},
    Phone:{label :'Phone'},
    Mobile:{label :'Mobile'},
    Enabled:{label :'Enabled'},
    Token:{label :'Token'},
    MsbAccount:{Heading:'MsbAccount',
        Username:{header:'Username'},
        Password:{header:'Password'},
        Account:{header:'Account'},
        Email:{header:'Email'},
        Phone:{header:'Phone'},
        Mobile:{header:'Mobile'},
        Enabled:{header:'Enabled'},
        Token:{header:'Token'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    req.session.previouspath = 'searchMsbAccount?'+req._parsedUrl.query;
    dao.searchMsbAccount(jsonObj,function(err,rows) {
        parameter = {
            session: req.session,
            cookies: req.cookies,
            resource: appresource,
            dateFormat: dateFormat,
            records: rows,
        }
        res.render('MsbAccountSearchPage',parameter);
        console.log(parameter);        
    })
});

module.exports = router;
