/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'MsbSubscriberSearch',
    Heading:'MsbSubscriber',
    Subscriber:{label :'Subscriber'},
    Password:{label :'Password'},
    Name:{label :'Name'},
    Email:{label :'Email'},
    Creationdate:{label :'Creationdate'},
    Modificationdate:{label :'Modificationdate'},
    Subtype:{label :'Subtype'},
    Account:{label :'Account'},
    Userkey:{label :'Userkey'},
    MsbSubscriber:{Heading:'MsbSubscriber',
        Subscriber:{header:'Subscriber'},
        Password:{header:'Password'},
        Name:{header:'Name'},
        Email:{header:'Email'},
        Creationdate:{header:'Creationdate'},
        Modificationdate:{header:'Modificationdate'},
        Subtype:{header:'Subtype'},
        Account:{header:'Account'},
        Userkey:{header:'Userkey'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    req.session.previouspath = 'searchMsbSubscriber?'+req._parsedUrl.query;
    dao.searchMsbSubscriber(jsonObj,function(err,rows) {
        parameter = {
            session: req.session,
            cookies: req.cookies,
            resource: appresource,
            dateFormat: dateFormat,
            records: rows,
        }
        res.render('MsbSubscriberSearchPage',parameter);
        console.log(parameter);        
    })
});

module.exports = router;
