/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'MsbSessionSearch',
    Heading:'MsbSession',
    Sessionid:{label :'Sessionid'},
    Subscriber:{label :'Subscriber'},
    Domain:{label :'Domain'},
    Ipaddress:{label :'Ipaddress'},
    Ipport:{label :'Ipport'},
    Protocol:{label :'Protocol'},
    Starttime:{label :'Starttime'},
    Endtime:{label :'Endtime'},
    Resource:{label :'Resource'},
    Presence:{label :'Presence'},
    Status:{label :'Status'},
    MsbSession:{Heading:'MsbSession',
        Sessionid:{header:'Sessionid'},
        Subscriber:{header:'Subscriber'},
        Domain:{header:'Domain'},
        Ipaddress:{header:'Ipaddress'},
        Ipport:{header:'Ipport'},
        Protocol:{header:'Protocol'},
        Starttime:{header:'Starttime'},
        Endtime:{header:'Endtime'},
        Resource:{header:'Resource'},
        Presence:{header:'Presence'},
        Status:{header:'Status'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    req.session.previouspath = 'searchMsbSession?'+req._parsedUrl.query;
    dao.searchMsbSession(jsonObj,function(err,rows) {
        parameter = {
            session: req.session,
            cookies: req.cookies,
            resource: appresource,
            dateFormat: dateFormat,
            records: rows,
        }
        res.render('MsbSessionSearchPage',parameter);
        console.log(parameter);        
    })
});

module.exports = router;
