/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'MsbPubsubSearch',
    Heading:'MsbPubsub',
    Serviceid:{label :'Serviceid'},
    Protocol:{label :'Protocol'},
    Description:{label :'Description'},
    MsbPubsub:{Heading:'MsbPubsub',
        Serviceid:{header:'Serviceid'},
        Protocol:{header:'Protocol'},
        Description:{header:'Description'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    req.session.previouspath = 'searchMsbPubsub?'+req._parsedUrl.query;
    dao.searchMsbPubsub(jsonObj,function(err,rows) {
        parameter = {
            session: req.session,
            cookies: req.cookies,
            resource: appresource,
            dateFormat: dateFormat,
            records: rows,
        }
        res.render('MsbPubsubSearchPage',parameter);
        console.log(parameter);        
    })
});

module.exports = router;
