/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'MsbPresenceSearch',
    Heading:'MsbPresence',
    Subscriber:{label :'Subscriber'},
    Offlinepresence:{label :'Offlinepresence'},
    Offlinedate:{label :'Offlinedate'},
    MsbPresence:{Heading:'MsbPresence',
        Subscriber:{header:'Subscriber'},
        Offlinepresence:{header:'Offlinepresence'},
        Offlinedate:{header:'Offlinedate'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    req.session.previouspath = 'searchMsbPresence?'+req._parsedUrl.query;
    dao.searchMsbPresence(jsonObj,function(err,rows) {
        parameter = {
            session: req.session,
            cookies: req.cookies,
            resource: appresource,
            dateFormat: dateFormat,
            records: rows,
        }
        res.render('MsbPresenceSearchPage',parameter);
        console.log(parameter);        
    })
});

module.exports = router;
