/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'MsbPersistentLoginsSearch',
    Heading:'MsbPersistentLogins',
    Username:{label :'Username'},
    Series:{label :'Series'},
    Token:{label :'Token'},
    LastUsed:{label :'LastUsed'},
    MsbPersistentLogins:{Heading:'MsbPersistentLogins',
        Username:{header:'Username'},
        Series:{header:'Series'},
        Token:{header:'Token'},
        LastUsed:{header:'LastUsed'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    req.session.previouspath = 'searchMsbPersistentLogins?'+req._parsedUrl.query;
    dao.searchMsbPersistentLogins(jsonObj,function(err,rows) {
        parameter = {
            session: req.session,
            cookies: req.cookies,
            resource: appresource,
            dateFormat: dateFormat,
            records: rows,
        }
        res.render('MsbPersistentLoginsSearchPage',parameter);
        console.log(parameter);        
    })
});

module.exports = router;
