/*
 * script route generated by KOMA
 * @author : Yan Yan Purdiansah
 */    
var express = require('express');
var router = express.Router();
var dateFormat = require('dateformat');    
var database = require('./dao');
var dao = new database.Dao();    
var sessionChecker = require('./security');
var appresource = {
    Title:'MsbPubsubnodegroupsSearch',
    Heading:'MsbPubsubnodegroups',
    Serviceid:{label :'Serviceid'},
    Nodeid:{label :'Nodeid'},
    Rostergroup:{label :'Rostergroup'},
    MsbPubsubnodegroups:{Heading:'MsbPubsubnodegroups',
        Serviceid:{header:'Serviceid'},
        Nodeid:{header:'Nodeid'},
        Rostergroup:{header:'Rostergroup'},
        },
    }

router.get('/', sessionChecker, function(req, res, next) {
    var jsonObj = req.query;
    if(jsonObj.rowid===undefined) jsonObj.rowid = 0;
    req.session.previouspath = 'searchMsbPubsubnodegroups?'+req._parsedUrl.query;
    dao.searchMsbPubsubnodegroups(jsonObj,function(err,rows) {
        parameter = {
            session: req.session,
            cookies: req.cookies,
            resource: appresource,
            dateFormat: dateFormat,
            records: rows,
        }
        res.render('MsbPubsubnodegroupsSearchPage',parameter);
        console.log(parameter);        
    })
});

module.exports = router;
